<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>Space Shooter Website</RootNamespace>
    <AssemblyName>$(AssemblyName.Replace(' ', '_'))</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <Content Remove="wwwroot\GameLogic.js" />
  </ItemGroup>

  <ItemGroup>
    <None Include="wwwroot\Js\GameLogic.js" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Server" Version="8.0.22" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Client Manager - API\Client Manager - API.csproj" />
    <ProjectReference Include="..\..\Model\Model.csproj" />
    <ProjectReference Include="..\Space Shooter Website.Client\Space Shooter Website.Client.csproj" />
  </ItemGroup>

</Project>
